// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzeqtohcyusdorwyztuq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6ZXF0b2hjeXVzZG9yd3l6dHVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MTcwNjIsImV4cCI6MjA2MDE5MzA2Mn0.odIPeqPbt1N6iLhxqWBezq0x2vm--Yj6hG6060BxgxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);